pipeline:
  identifier: Build_Pooja19S_test_app_1721805717307
  name: Build test-app
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Pooja19S/test-app
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
        type: CI
        delegateSelectors:
          - docker-delegate
  delegateSelectors:
    - docker-delegate
